/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_BLOCK_ENGINE_BLOCK_ENGINE_PB_H_INCLUDED
#define PB_BLOCK_ENGINE_BLOCK_ENGINE_PB_H_INCLUDED
#include "../../../third_party/nanopb/pb_firedancer.h"
#include "packet.pb.h"
#include "shared.pb.h"
#include "bundle.pb.h"
#include "timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Scheduling strategy the block engine runs for this validator session. */
typedef enum _block_engine_SchedulingStrategy {
    block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_UNSPECIFIED = 0,
    /* First-in, first-out continuous availability sequencing. */
    block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_FIFO = 1,
    /* Frequent batch auction: discrete batches ordered by priority fees and tips. */
    block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_FBA = 2,
    /* Maximum revenue strategy: continuous streaming with revenue-prioritizing selection. */
    block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_MREV = 3
} block_engine_SchedulingStrategy;

/* Struct definitions */
typedef struct _block_engine_SubscribePacketsRequest {
    char dummy_field;
} block_engine_SubscribePacketsRequest;

typedef struct _block_engine_SubscribePacketsResponse {
    bool has_header;
    shared_Header header;
    bool has_batch;
    packet_PacketBatch batch;
} block_engine_SubscribePacketsResponse;

typedef struct _block_engine_SubscribeBundlesRequest {
    char dummy_field;
} block_engine_SubscribeBundlesRequest;

typedef struct _block_engine_SubscribeBundlesResponse {
    pb_callback_t bundles;
} block_engine_SubscribeBundlesResponse;

typedef struct _block_engine_BlockBuilderFeeInfoRequest {
    char dummy_field;
} block_engine_BlockBuilderFeeInfoRequest;

typedef struct _block_engine_BlockBuilderFeeInfoResponse {
    char pubkey[45];
    /* commission (0-100) */
    uint64_t commission;
} block_engine_BlockBuilderFeeInfoResponse;

typedef struct _block_engine_SubmitLeaderWindowInfoRequest {
    bool has_start_timestamp;
    google_protobuf_Timestamp start_timestamp;
    uint64_t slot;
} block_engine_SubmitLeaderWindowInfoRequest;

typedef struct _block_engine_SubmitLeaderWindowInfoResponse {
    char dummy_field;
} block_engine_SubmitLeaderWindowInfoResponse;

/* Selects the scheduling strategy for this validator session. */
typedef struct _block_engine_SetStrategyRequest {
    block_engine_SchedulingStrategy strategy;
} block_engine_SetStrategyRequest;

typedef struct _block_engine_SetStrategyResponse {
    char dummy_field;
} block_engine_SetStrategyResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _block_engine_SchedulingStrategy_MIN block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_UNSPECIFIED
#define _block_engine_SchedulingStrategy_MAX block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_MREV
#define _block_engine_SchedulingStrategy_ARRAYSIZE ((block_engine_SchedulingStrategy)(block_engine_SchedulingStrategy_SCHEDULING_STRATEGY_MREV+1))









#define block_engine_SetStrategyRequest_strategy_ENUMTYPE block_engine_SchedulingStrategy



/* Initializer values for message structs */
#define block_engine_SubscribePacketsRequest_init_default {0}
#define block_engine_SubscribePacketsResponse_init_default {false, shared_Header_init_default, false, packet_PacketBatch_init_default}
#define block_engine_SubscribeBundlesRequest_init_default {0}
#define block_engine_SubscribeBundlesResponse_init_default {{{NULL}, NULL}}
#define block_engine_BlockBuilderFeeInfoRequest_init_default {0}
#define block_engine_BlockBuilderFeeInfoResponse_init_default {"", 0}
#define block_engine_SubmitLeaderWindowInfoRequest_init_default {false, google_protobuf_Timestamp_init_default, 0}
#define block_engine_SubmitLeaderWindowInfoResponse_init_default {0}
#define block_engine_SetStrategyRequest_init_default {_block_engine_SchedulingStrategy_MIN}
#define block_engine_SetStrategyResponse_init_default {0}
#define block_engine_SubscribePacketsRequest_init_zero {0}
#define block_engine_SubscribePacketsResponse_init_zero {false, shared_Header_init_zero, false, packet_PacketBatch_init_zero}
#define block_engine_SubscribeBundlesRequest_init_zero {0}
#define block_engine_SubscribeBundlesResponse_init_zero {{{NULL}, NULL}}
#define block_engine_BlockBuilderFeeInfoRequest_init_zero {0}
#define block_engine_BlockBuilderFeeInfoResponse_init_zero {"", 0}
#define block_engine_SubmitLeaderWindowInfoRequest_init_zero {false, google_protobuf_Timestamp_init_zero, 0}
#define block_engine_SubmitLeaderWindowInfoResponse_init_zero {0}
#define block_engine_SetStrategyRequest_init_zero {_block_engine_SchedulingStrategy_MIN}
#define block_engine_SetStrategyResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define block_engine_SubscribePacketsResponse_header_tag 1
#define block_engine_SubscribePacketsResponse_batch_tag 2
#define block_engine_SubscribeBundlesResponse_bundles_tag 1
#define block_engine_BlockBuilderFeeInfoResponse_pubkey_tag 1
#define block_engine_BlockBuilderFeeInfoResponse_commission_tag 2
#define block_engine_SubmitLeaderWindowInfoRequest_start_timestamp_tag 1
#define block_engine_SubmitLeaderWindowInfoRequest_slot_tag 2
#define block_engine_SetStrategyRequest_strategy_tag 1

/* Struct field encoding specification for nanopb */
#define block_engine_SubscribePacketsRequest_FIELDLIST(X, a) \

#define block_engine_SubscribePacketsRequest_CALLBACK NULL
#define block_engine_SubscribePacketsRequest_DEFAULT NULL

#define block_engine_SubscribePacketsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  batch,             2)
#define block_engine_SubscribePacketsResponse_CALLBACK NULL
#define block_engine_SubscribePacketsResponse_DEFAULT NULL
#define block_engine_SubscribePacketsResponse_header_MSGTYPE shared_Header
#define block_engine_SubscribePacketsResponse_batch_MSGTYPE packet_PacketBatch

#define block_engine_SubscribeBundlesRequest_FIELDLIST(X, a) \

#define block_engine_SubscribeBundlesRequest_CALLBACK NULL
#define block_engine_SubscribeBundlesRequest_DEFAULT NULL

#define block_engine_SubscribeBundlesResponse_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  bundles,           1)
#define block_engine_SubscribeBundlesResponse_CALLBACK pb_default_field_callback
#define block_engine_SubscribeBundlesResponse_DEFAULT NULL
#define block_engine_SubscribeBundlesResponse_bundles_MSGTYPE bundle_BundleUuid

#define block_engine_BlockBuilderFeeInfoRequest_FIELDLIST(X, a) \

#define block_engine_BlockBuilderFeeInfoRequest_CALLBACK NULL
#define block_engine_BlockBuilderFeeInfoRequest_DEFAULT NULL

#define block_engine_BlockBuilderFeeInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   pubkey,            1) \
X(a, STATIC,   SINGULAR, UINT64,   commission,        2)
#define block_engine_BlockBuilderFeeInfoResponse_CALLBACK NULL
#define block_engine_BlockBuilderFeeInfoResponse_DEFAULT NULL

#define block_engine_SubmitLeaderWindowInfoRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  start_timestamp,   1) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              2)
#define block_engine_SubmitLeaderWindowInfoRequest_CALLBACK NULL
#define block_engine_SubmitLeaderWindowInfoRequest_DEFAULT NULL
#define block_engine_SubmitLeaderWindowInfoRequest_start_timestamp_MSGTYPE google_protobuf_Timestamp

#define block_engine_SubmitLeaderWindowInfoResponse_FIELDLIST(X, a) \

#define block_engine_SubmitLeaderWindowInfoResponse_CALLBACK NULL
#define block_engine_SubmitLeaderWindowInfoResponse_DEFAULT NULL

#define block_engine_SetStrategyRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    strategy,          1)
#define block_engine_SetStrategyRequest_CALLBACK NULL
#define block_engine_SetStrategyRequest_DEFAULT NULL

#define block_engine_SetStrategyResponse_FIELDLIST(X, a) \

#define block_engine_SetStrategyResponse_CALLBACK NULL
#define block_engine_SetStrategyResponse_DEFAULT NULL

extern const pb_msgdesc_t block_engine_SubscribePacketsRequest_msg;
extern const pb_msgdesc_t block_engine_SubscribePacketsResponse_msg;
extern const pb_msgdesc_t block_engine_SubscribeBundlesRequest_msg;
extern const pb_msgdesc_t block_engine_SubscribeBundlesResponse_msg;
extern const pb_msgdesc_t block_engine_BlockBuilderFeeInfoRequest_msg;
extern const pb_msgdesc_t block_engine_BlockBuilderFeeInfoResponse_msg;
extern const pb_msgdesc_t block_engine_SubmitLeaderWindowInfoRequest_msg;
extern const pb_msgdesc_t block_engine_SubmitLeaderWindowInfoResponse_msg;
extern const pb_msgdesc_t block_engine_SetStrategyRequest_msg;
extern const pb_msgdesc_t block_engine_SetStrategyResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define block_engine_SubscribePacketsRequest_fields &block_engine_SubscribePacketsRequest_msg
#define block_engine_SubscribePacketsResponse_fields &block_engine_SubscribePacketsResponse_msg
#define block_engine_SubscribeBundlesRequest_fields &block_engine_SubscribeBundlesRequest_msg
#define block_engine_SubscribeBundlesResponse_fields &block_engine_SubscribeBundlesResponse_msg
#define block_engine_BlockBuilderFeeInfoRequest_fields &block_engine_BlockBuilderFeeInfoRequest_msg
#define block_engine_BlockBuilderFeeInfoResponse_fields &block_engine_BlockBuilderFeeInfoResponse_msg
#define block_engine_SubmitLeaderWindowInfoRequest_fields &block_engine_SubmitLeaderWindowInfoRequest_msg
#define block_engine_SubmitLeaderWindowInfoResponse_fields &block_engine_SubmitLeaderWindowInfoResponse_msg
#define block_engine_SetStrategyRequest_fields &block_engine_SetStrategyRequest_msg
#define block_engine_SetStrategyResponse_fields &block_engine_SetStrategyResponse_msg

/* Maximum encoded size of messages (where known) */
/* block_engine_SubscribeBundlesResponse_size depends on runtime parameters */
#define BLOCK_ENGINE_BLOCK_ENGINE_PB_H_MAX_SIZE  block_engine_BlockBuilderFeeInfoResponse_size
#define block_engine_BlockBuilderFeeInfoRequest_size 0
#define block_engine_BlockBuilderFeeInfoResponse_size 57
#define block_engine_SetStrategyRequest_size     2
#define block_engine_SetStrategyResponse_size    0
#define block_engine_SubmitLeaderWindowInfoRequest_size 35
#define block_engine_SubmitLeaderWindowInfoResponse_size 0
#define block_engine_SubscribeBundlesRequest_size 0
#define block_engine_SubscribePacketsRequest_size 0
#if defined(packet_PacketBatch_size)
#define block_engine_SubscribePacketsResponse_size (32 + packet_PacketBatch_size)
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
