/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_BLOCK_BLOCK_PB_H_INCLUDED
#define PB_BLOCK_BLOCK_PB_H_INCLUDED
#include "../../../third_party/nanopb/pb_firedancer.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* An ordered list of transactions targeting a given slot. */
typedef struct _block_Block {
    /* Slot target for these transactions. */
    uint64_t slot; /* Field numbers 2-14 left free for future block-level metadata. */
    /* Transactions in execution order. */
    pb_callback_t transactions;
} block_Block;

typedef PB_BYTES_ARRAY_T(4096) block_Transaction_transaction_t;
/* A single transaction; field numbers match builder-protos `block.Transaction`. */
typedef struct _block_Transaction {
    /* Raw transaction bytes. */
    block_Transaction_transaction_t transaction;
    /* Bundle uuid; 0 == standalone transaction, nonzero == revert protected bundle.
 Consecutive transactions sharing the same bundle_id form one bundle, of any length. */
    uint64_t bundle_id;
} block_Transaction;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define block_Block_init_default                 {0, {{NULL}, NULL}}
#define block_Transaction_init_default           {{0, {0}}, 0}
#define block_Block_init_zero                    {0, {{NULL}, NULL}}
#define block_Transaction_init_zero              {{0, {0}}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define block_Block_slot_tag                     1
#define block_Block_transactions_tag             15
#define block_Transaction_transaction_tag        1
#define block_Transaction_bundle_id_tag          3

/* Struct field encoding specification for nanopb */
#define block_Block_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   slot,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  transactions,     15)
#define block_Block_CALLBACK pb_default_field_callback
#define block_Block_DEFAULT NULL
#define block_Block_transactions_MSGTYPE block_Transaction

#define block_Transaction_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    transaction,       1) \
X(a, STATIC,   SINGULAR, UINT64,   bundle_id,         3)
#define block_Transaction_CALLBACK NULL
#define block_Transaction_DEFAULT NULL

extern const pb_msgdesc_t block_Block_msg;
extern const pb_msgdesc_t block_Transaction_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define block_Block_fields &block_Block_msg
#define block_Transaction_fields &block_Transaction_msg

/* Maximum encoded size of messages (where known) */
/* block_Block_size depends on runtime parameters */
#define BLOCK_BLOCK_PB_H_MAX_SIZE                block_Transaction_size
#define block_Transaction_size                   4110

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
