/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "block.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(block_Block, block_Block, AUTO)


PB_BIND(block_Transaction, block_Transaction, 4)



