/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_TPU_TPU_PB_H_INCLUDED
#define PB_TPU_TPU_PB_H_INCLUDED
#include "../../../ballet/nanopb/pb_firedancer.h"
#include "packet.pb.h"
#include "shared.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _tpu_GetTpuConfigsRequest {
    char dummy_field;
} tpu_GetTpuConfigsRequest;

typedef struct _tpu_GetTpuConfigsResponse {
    bool has_tpu;
    shared_Socket tpu;
    bool has_tpu_forward;
    shared_Socket tpu_forward;
} tpu_GetTpuConfigsResponse;

typedef struct _tpu_SubscribePacketsRequest {
    char dummy_field;
} tpu_SubscribePacketsRequest;

typedef struct _tpu_SubscribePacketsResponse {
    bool has_header;
    shared_Header header;
    pb_size_t which_msg;
    union {
        shared_Heartbeat heartbeat;
        packet_PacketBatch batch;
    } msg;
} tpu_SubscribePacketsResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define tpu_GetTpuConfigsRequest_init_default    {0}
#define tpu_GetTpuConfigsResponse_init_default   {false, shared_Socket_init_default, false, shared_Socket_init_default}
#define tpu_SubscribePacketsRequest_init_default {0}
#define tpu_SubscribePacketsResponse_init_default {false, shared_Header_init_default, 0, {shared_Heartbeat_init_default}}
#define tpu_GetTpuConfigsRequest_init_zero       {0}
#define tpu_GetTpuConfigsResponse_init_zero      {false, shared_Socket_init_zero, false, shared_Socket_init_zero}
#define tpu_SubscribePacketsRequest_init_zero    {0}
#define tpu_SubscribePacketsResponse_init_zero   {false, shared_Header_init_zero, 0, {shared_Heartbeat_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define tpu_GetTpuConfigsResponse_tpu_tag        1
#define tpu_GetTpuConfigsResponse_tpu_forward_tag 2
#define tpu_SubscribePacketsResponse_header_tag  1
#define tpu_SubscribePacketsResponse_heartbeat_tag 2
#define tpu_SubscribePacketsResponse_batch_tag   3

/* Struct field encoding specification for nanopb */
#define tpu_GetTpuConfigsRequest_FIELDLIST(X, a) \

#define tpu_GetTpuConfigsRequest_CALLBACK NULL
#define tpu_GetTpuConfigsRequest_DEFAULT NULL

#define tpu_GetTpuConfigsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tpu,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tpu_forward,       2)
#define tpu_GetTpuConfigsResponse_CALLBACK NULL
#define tpu_GetTpuConfigsResponse_DEFAULT NULL
#define tpu_GetTpuConfigsResponse_tpu_MSGTYPE shared_Socket
#define tpu_GetTpuConfigsResponse_tpu_forward_MSGTYPE shared_Socket

#define tpu_SubscribePacketsRequest_FIELDLIST(X, a) \

#define tpu_SubscribePacketsRequest_CALLBACK NULL
#define tpu_SubscribePacketsRequest_DEFAULT NULL

#define tpu_SubscribePacketsResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,heartbeat,msg.heartbeat),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,batch,msg.batch),   3)
#define tpu_SubscribePacketsResponse_CALLBACK NULL
#define tpu_SubscribePacketsResponse_DEFAULT NULL
#define tpu_SubscribePacketsResponse_header_MSGTYPE shared_Header
#define tpu_SubscribePacketsResponse_msg_heartbeat_MSGTYPE shared_Heartbeat
#define tpu_SubscribePacketsResponse_msg_batch_MSGTYPE packet_PacketBatch

extern const pb_msgdesc_t tpu_GetTpuConfigsRequest_msg;
extern const pb_msgdesc_t tpu_GetTpuConfigsResponse_msg;
extern const pb_msgdesc_t tpu_SubscribePacketsRequest_msg;
extern const pb_msgdesc_t tpu_SubscribePacketsResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define tpu_GetTpuConfigsRequest_fields &tpu_GetTpuConfigsRequest_msg
#define tpu_GetTpuConfigsResponse_fields &tpu_GetTpuConfigsResponse_msg
#define tpu_SubscribePacketsRequest_fields &tpu_SubscribePacketsRequest_msg
#define tpu_SubscribePacketsResponse_fields &tpu_SubscribePacketsResponse_msg

/* Maximum encoded size of messages (where known) */
#if defined(packet_PacketBatch_size)
union tpu_SubscribePacketsResponse_msg_size_union {char f3[(6 + packet_PacketBatch_size)]; char f0[13];};
#endif
#define tpu_GetTpuConfigsRequest_size            0
#define tpu_SubscribePacketsRequest_size         0
#if defined(shared_Socket_size) && defined(shared_Socket_size)
#define tpu_GetTpuConfigsResponse_size           (12 + shared_Socket_size + shared_Socket_size)
#endif
#if defined(packet_PacketBatch_size)
#define TPU_TPU_PB_H_MAX_SIZE                    tpu_SubscribePacketsResponse_size
#define tpu_SubscribePacketsResponse_size        (26 + sizeof(union tpu_SubscribePacketsResponse_msg_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
