/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "tpu.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(tpu_GetTpuConfigsRequest, tpu_GetTpuConfigsRequest, AUTO)


PB_BIND(tpu_GetTpuConfigsResponse, tpu_GetTpuConfigsResponse, AUTO)


PB_BIND(tpu_SubscribePacketsRequest, tpu_SubscribePacketsRequest, AUTO)


PB_BIND(tpu_SubscribePacketsResponse, tpu_SubscribePacketsResponse, AUTO)



